### ISSUE TITLE
DataFrame rows order changes when deep copying a pypowsybl network

### ISSUE THREAD

**Issue by vinault** [powsybl/pypowsybl-grid2opbackend#3]
### Describe the current behavior

This behavior relates more to pypowsybl but it has heavy implications on the pypowsybl-grid2opbackend so I'd like to start the discussion here.
After deepcopying the pypowsybl grid (to save the initial grid) the loads DataFrame has different rows order than the original loads DataFrame.

This is a problem because the grid2op backend relies on the rows order (At least this is the case for the PandaPowerBackend) to retrieve the topo_vect. See ([grid2op.Backend.PandaPowerBackend._get_topo_vect](https://github.com/rte-france/Grid2Op/blob/master/grid2op/Backend/PandaPowerBackend.py#L1357))

### Describe the expected behavior

Rows order should be the same

### Describe the steps

```python
import pypowsybl.network as pn
import copy
network = pn.create_ieee14()
print(network.get_loads())
network_deep_copy = copy.deepcopy(network)
print(network_deep_copy.get_loads())
```

![image](https://github.com/powsybl/pypowsybl-grid2opbackend/assets/25577263/d8d76a6f-9e34-4b4e-be81-cbb915af0464)

### Extra Information

@BDonnot : Have you ever bumped into a similar problem? I saw you were the one originally asking for the deepcopy feature from pypowsybl in https://github.com/powsybl/pypowsybl/issues/117

@marota

**Comment by BDonnot** [comment]
Hello,

I don't remember having this kind of issue. But I tested pypowsybl before the deep copy I could not come across this deep copy issue.

Grid2op indeed requires that the order of all elements are constant, for loads, generators, shunts, lines etc What you can do, but it might  cost a bit of time is to sort the data frame by the names of the element.

**Comment by vinault** [comment]
Thanks @BDonnot for the quick feedback ! 
I guess we can for now overload the pypowsybl.Network.get_* methods to make to always sort the index of the DataFrames before returning them.
I'll also push the issue to the pypowsybl repo as this is probably not the expected behavior.

**Comment by tschuppr** [comment]
Problem fixed with [SortedNetwork class implementation](https://github.com/powsybl/pypowsybl-grid2opbackend/blob/main/src/Backend/network.py)
