### ISSUE TITLE
CD/CI integration

### ISSUE THREAD

**Issue by marota** [powsybl/pypowsybl-grid2opbackend#6]
### Describe the current behavior

Test are not checked automatically after each commit currently

### Describe the expected behavior

test each new commit (or PR at least)

### Describe the motivation

No regressions, robust collaboration and PR from external contributors

### Extra Information

SonarCub or CircleCI ? Circle-CI is very much used for open-source projects for assets not yet used in production

**Comment by marota** [comment]
Mettre des tests sur des github actions

**Comment by marota** [comment]
Make sure to be able to install the powsybl/pypowsybl branch (until it is properly integrated) when running automatic CI worksflow with tests. 
See example in https://github.com/powsybl/pypowsybl/tree/main/.github/workflows

**Comment by tschuppr** [comment]
The CI/CD was install working thanks to several commits and the last one used to validate it was [9c5c5b7](https://github.com/powsybl/pypowsybl-grid2opbackend/commit/9c5c5b79f5011bde96dd43b48c745f7626fce21b)
