### ISSUE TITLE
Make it a python package & Publish

### ISSUE THREAD

**Issue by marota** [powsybl/pypowsybl-grid2opbackend#9]
### Describe the current behavior

Import are currently done this way
from src.Backend.PowsyblBackend import PowsyblBackend

This should rather get imported as a python package

### Describe the expected behavior

from PowsyblGrid2opBackend import PowsyblBackend

If the package is called PowsyblGrid2opBackend for instance
Should be published on pyPI

**Comment by yojvr** [comment]
Link to the package on PyPI: https://pypi.org/project/pypowsybl_grid2opbackend/.
